//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildCars.Data.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact : IValidatableObject
    {
        public int ContactId { get; set; }
        public string ContactName { get; set; }
        [EmailAddress]
        public string ContactEmail { get; set; }
        [Phone]
        public string ContactPhone { get; set; }
        public string ContactMessage { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (string.IsNullOrEmpty(ContactName))
            {
                errors.Add(new ValidationResult("You must enter a Name", new[] { "ContactName"}));
            }

            if (string.IsNullOrEmpty(ContactMessage))
            {
                errors.Add(new ValidationResult("You must enter a Message", new[] { "ContactMessage" }));
            }

            if (string.IsNullOrEmpty(ContactEmail) && string.IsNullOrEmpty(ContactPhone))
            {
                errors.Add(new ValidationResult("You must enter either Phone or Email", new[] { "ContactPhone","ContactEmail" }));
            }

            return errors;
        }
    }
}
