//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildCars.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Special
    {
        public int SpecialId { get; set; }
        public string SpecialTitle { get; set; }
        public string SpecialNote { get; set; }
    }
}
